include("analyse_closed_order.jl")
include("check_for_new_closed.jl")
include("check_grid_buy.jl")
include("check_grid_sell.jl")
include("create_trade_grid.jl")
include("finish_grid_bot.jl")
include("freeze_orders.jl")
include("get_buy_value.jl")
include("get_current_volume.jl")
include("get_grid_bots.jl")
include("get_next_gridpoints.jl")
include("init_grid_bot.jl")
include("place_grid_order.jl")
include("place_init_grid_order.jl")
include("update_status.jl")

